### ISSUE TITLE
Repopulate repeater fields on validation fail?

### ISSUE THREAD

**Issue by sitrick2** [TypeRocket/laravel#3]
I know validation handling exists in the WordPress version of TypeRocket, but it doesn't look like it's made it into this version of the plugin? What's the best way to populate repeater fields with form data when a request fails validation and redirects back to the form?

**Comment by kevindees** [comment]
Hey @sitrick2 

We do not have it in this version because you can use the system used in Laravel. Repeater fields use arrays as their data do you can use the Laravel validation for array to get what you are looking for.

https://laravel.com/docs/5.5/validation#validating-arrays

Thanks,
Kevin

**Comment by sitrick2** [comment]
Thanks for the quick response Kevin, I think I was maybe unclear about the issue I'm having. I can validate items without any issue, it's just that on a form failure, after laravel redirects back to the form with an error message flashed, none of the data in repeater fields persists -- a user has to go through and re-create each repeater field instance, and repopulate the form data. For example, on a form creating an Event that has many EventAddresses, with a TypeRocket repeater field representing each EventAddress instance, if the form submit fails (i.e., an invalid event date, etc), all the EventAddress instances are wiped clean from the form, and the user has to add each EventAddress and re-fill out address_1, address_2, city, state, zip, etc.

Is there support for repopulating these fields on form validation failure? I may just be being dumb about this, hah.

**Comment by kevindees** [comment]
Hey @sitrick2 

You should be able to get the fields to populate using the old data by passing the request to the form.

```php
/** @var \Illuminate\Http\Request $request  */
$form->setRequest( $request );
```

If the validation fails redirect with input. I think that will do it.

```php
Route::post('/page/1', function () {
    // Validate the request...

    return back()->withInput();
});
```

Let me know if that helps.

**Comment by sitrick2** [comment]
Hi @kevindees, actually when you run Validator's validate() function it calls withInput() on the returned redirect by default. I've actually confirmed that the request object is present with all the form data, it's just not getting populated by any of the TypeRocket fields.

Here's are the relevant code fragments from my view:

View:

```
{!! Form::open(['method' => 'POST', 'route' => 'events.store', 'files' => true ]) !!}
<!-- non TypeRocket form element that successfully auto-populates on form validation fail --!>
<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
	{!! Form::label('title', 'Title') !!}
        {!! Form::text('title', null, ['class' => 'form-control', 'required' => 'required']) !!}
	<small class="text-danger">{{ $errors->first('title') }}</small>
</div>
...
<?php
//TypeRocket form element that does not auto-populate on form validation fail
	$form = new \TypeRocket\Form('Models\Event', 'create');
	echo $form->repeater('Event Location(s)')->setFields([
	    $form->text('venue', ['class' => 'form-control'],['label' => 'Venue Name']),
	    $form->text('address_1', ['class' => 'form-control'], ['label' => 'Address']),
            $form->text('address_2', ['class' => 'form-control'], ['label' => 'Suite/Building #']),
            $form->text('city', ['class' => 'form-control'], ['label' => 'City']),
            $form->select('state', ['class' => 'form-control'], ['label' => 'State'])->setOptions(\App\Models\EventAddress::$stateVals),
            $form->text('postal', ['class' => 'form-control'], ['label' => "Zip/Postal Code"])
        ]);
?>
...
{!! Form::submit('Add Event', ['class'=>'btn btn-primary btn-action pull-right']) !!}
{!! Form::close() !!}
```

I'd include the controller code but that's honestly pretty simple, it's just running $request->validate() on the input data.

**Comment by kevindees** [comment]
Try this,

Pass the request to the view and set the form to use it. This line is what you should note;

```php
$form = (new \TypeRocket\Form('Models\Event', 'create'))->setRequest( $request );
```

```php
<?php
      //TypeRocket form element that does not auto-populate on form validation fail
	$form = (new \TypeRocket\Form('Models\Event', 'create'))->setRequest( $request );
	echo $form->repeater('Event Location(s)')->setFields([
	    $form->text('venue', ['class' => 'form-control'],['label' => 'Venue Name']),
	    $form->text('address_1', ['class' => 'form-control'], ['label' => 'Address']),
            $form->text('address_2', ['class' => 'form-control'], ['label' => 'Suite/Building #']),
            $form->text('city', ['class' => 'form-control'], ['label' => 'City']),
            $form->select('state', ['class' => 'form-control'], ['label' => 'State'])->setOptions(\App\Models\EventAddress::$stateVals),
            $form->text('postal', ['class' => 'form-control'], ['label' => "Zip/Postal Code"])
        ]);
?>
```

**Comment by sitrick2** [comment]
Hi @kevindees, just got a chance to try this. Still no dice.

**Comment by kevindees** [comment]
@sitrick2 

Have you looked at this? https://github.com/TypeRocket/laravel#request-old-input

I normally setup the form in the controller because old data needs to be pulled in before the first line of output.

Thanks,
Kevin

**Comment by sitrick2** [comment]
Sorry, just got back to this. By accident I made the setRequest call after initializing the object and it started behaving the way I wanted it to.

Thanks for all the help on this!
